packages:
  # all packages in direct subdirs of packages/
  - 'packages/**'

  # all packages in direct subdirs of docs/
  - 'docs/'

  # all packages in direct subdirs of examples/
  - 'examples/**'
